server:
    applicationConnectors:
        - type: http
          port: 5959
database: 
    driverClass: org.sqlite.JDBC
    user: admin 
    url: jdbc:sqlite:./pixlotto.db
imagePath: ./data/
lottoPath: ./lotto.csv